import { NextRequest, NextResponse } from "next/server";
import type { RowDataPacket } from "mysql2/promise";
import pool from "@/lib/db";
import { acquireCronLock, releaseCronLock, requireCronSecret } from "@/lib/cronSecurity";
import { refreshSubscriberChannel } from "@/lib/channelSubscriberRefresh";
import { CHANNEL_REFRESH_ELIGIBILITY_SQL, SUBSCRIBER_REFRESH_HOURS } from "@/lib/channelRefreshPolicy";
export const dynamic="force-dynamic";
const BATCH=Math.min(50,Math.max(1,Number(process.env.SUBSCRIBER_REFRESH_BATCH_SIZE||10)));
export async function GET(request:NextRequest){const unauthorized=requireCronSecret(request);if(unauthorized)return unauthorized;const lock=await acquireCronLock("update-subscribers",1800);if(!lock)return NextResponse.json({success:false,message:"Subscriber refresh already running"},{status:409});try{const [[setting]]:any=await pool.query("SELECT value FROM settings WHERE `key`='min_subscribers' LIMIT 1");const minimum=Math.max(0,Number(setting?.value||100));const [channels]=await pool.query<Array<RowDataPacket&Record<string,any>>>(`SELECT c.id,c.user_id,c.chat_id,c.channel_type,c.tracking_account,c.status,c.is_deleted,c.marketplace_admin_status,c.paused_reason,c.automation_suspension_status,c.automation_suspended_until,c.revenue_protection_status,c.under_review,c.settlement_excluded_until,c.below_minimum_since,c.below_minimum_success_count,c.monetization_paused_reason,u.status publisher_status,u.is_banned publisher_is_banned FROM channels c JOIN users u ON u.id=c.user_id WHERE ${CHANNEL_REFRESH_ELIGIBILITY_SQL} AND (c.subscribers_last_attempt_at IS NULL OR c.subscribers_last_attempt_at<=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ${SUBSCRIBER_REFRESH_HOURS} HOUR)) AND (c.subscribers_next_retry_at IS NULL OR c.subscribers_next_retry_at<=UTC_TIMESTAMP()) ORDER BY COALESCE(c.subscribers_last_attempt_at,'1970-01-01'),c.id LIMIT ${BATCH}`);const results=[];for(const channel of channels)results.push({id:channel.id,...await refreshSubscriberChannel(channel,minimum)});return NextResponse.json({success:true,processed:results.length,minimum,details:results});}catch(error){console.error("Subscriber refresh failed",error);return NextResponse.json({success:false,error:"subscriber_refresh_failed"},{status:500});}finally{await releaseCronLock(lock);}}
