-- Durable, shared Admin login abuse counters. No account identifiers or IPs
-- are stored directly; key_hash is a SHA-256 digest generated by the app.
CREATE TABLE IF NOT EXISTS admin_login_rate_limits (
  scope ENUM('account_ip', 'ip') NOT NULL,
  key_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  failure_count INT UNSIGNED NOT NULL DEFAULT 0,
  window_started_at DATETIME(3) NOT NULL,
  locked_until DATETIME(3) NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (scope, key_hash),
  KEY idx_admin_login_rate_limits_cleanup (updated_at),
  KEY idx_admin_login_rate_limits_lock (locked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
