import "server-only";
import type { ResultSetHeader,RowDataPacket } from "mysql2/promise";
import pool from "@/lib/db";
import { channelCampaignMatchesInventory } from "@/lib/channelAudience";
import { campaignExcludesChannel,loadCampaignExclusions } from "@/lib/campaignInventoryExclusions";
import { appendTelegramEntities,contentHash,editTelegramTeaser,fetchTeaserViews,opaqueTeaserToken,renderTeaserSuffix,teaserContentFits,teaserRetryDelaySeconds,teaserRetryExhausted,type TeaserCtaKey,type TelegramEntity } from "@/lib/teaser";

export type TeaserInsertReason="TARGETING_MISMATCH"|"CHANNEL_INACTIVE"|"PUBLISHER_INACTIVE"|"TEASER_DISABLED"|"EDIT_PERMISSION_MISSING"|"DAILY_LIMIT_REACHED"|"NO_SAFE_ORGANIC_SNAPSHOT"|"POST_TOO_LONG"|"POST_UNSUPPORTED"|"POST_ALREADY_HAS_TEASER"|"CAMPAIGN_INACTIVE"|"BUDGET_EXHAUSTED"|"INSUFFICIENT_BALANCE"|"DUPLICATE_PLACEMENT"|"SNAPSHOT_MESSAGE_ABSENT"|"SNAPSHOT_NOT_EDITABLE"|"SNAPSHOT_TERMINAL_TELEGRAM"|"TELEGRAM_RETRYABLE"|"TELEGRAM_TERMINAL"|"NO_CAMPAIGN";
type Snapshot={id:number;channel_id:number;publisher_id:number;telegram_chat_id:number;telegram_message_id:number;message_type:string;organic_text:string;entities:unknown;caption_entities:unknown;content_hash:string};
type Channel=RowDataPacket&{id:number;user_id:number;username:string|null;channel_type:string;tracking_account:number|null;categories:unknown;audience_continents:unknown;authoritative_country_code:string|null;authoritative_language_code:string|null;teaser_enabled:number;teaser_status:string;teaser_daily_limit:number;teaser_last_placement_message_id:number|null};
type Campaign=RowDataPacket&{id:number;user_id:number;status:string;teaser_enabled:number;teaser_cta_key:TeaserCtaKey;teaser_cpm:number;budget:number;ad_balance:number;category:string;continents:unknown;countries:unknown;languages:unknown};
const parseEntities=(value:unknown):TelegramEntity[]=>{if(Array.isArray(value))return value as TelegramEntity[];if(typeof value==="string")try{return JSON.parse(value) as TelegramEntity[];}catch{return [];}return [];};
const origin=()=>String(process.env.NEXT_PUBLIC_APP_URL||process.env.NEXT_PUBLIC_ADSGALAXY_APP_URL||"https://app.adsgalaxy.online").replace(/\/$/,"");
const LEASE_SECONDS=120;

/** Commits the exact intended mutation before Telegram I/O. Replaying that mutation is idempotent. */
export async function insertTeaserPlacement(input:{sourceUpdateId:number;campaignId?:number;channelId:number;snapshot:Snapshot;emergencyJobId?:number;overrideCampaignTargeting?:boolean}){
 const conn=await pool.getConnection();let committed=false;
 try{
  await conn.beginTransaction();
  const [channels]=await conn.query<Channel[]>(`SELECT ch.*,g.authoritative_country_code,g.authoritative_language_code FROM channels ch JOIN users p ON p.id=ch.user_id LEFT JOIN channel_geo_classifications g ON g.channel_id=ch.id WHERE ch.id=? AND ch.is_deleted=0 AND ch.status IN ('active','approved') AND p.status='active' AND p.is_banned=0 FOR UPDATE`,[input.channelId]);const ch=channels[0];
  if(!ch){await conn.rollback();return{ok:false as const,reason:"CHANNEL_INACTIVE" as TeaserInsertReason};}if(!ch.teaser_enabled){await conn.rollback();return{ok:false as const,reason:"TEASER_DISABLED" as TeaserInsertReason};}if(ch.teaser_status!=="active"){await conn.rollback();return{ok:false as const,reason:"EDIT_PERMISSION_MISSING" as TeaserInsertReason};}
  // A claim/orphan never consumes quota; only inserted_at does.
  const [quota]=await conn.query<Array<RowDataPacket&{n:number}>>("SELECT COUNT(*) n FROM teaser_placements WHERE channel_id=? AND inserted_at>=UTC_DATE()",[ch.id]);if(Number(quota[0]?.n)>=Number(ch.teaser_daily_limit)){await conn.rollback();return{ok:false as const,reason:"DAILY_LIMIT_REACHED" as TeaserInsertReason};}if(ch.teaser_last_placement_message_id&&input.snapshot.telegram_message_id-Number(ch.teaser_last_placement_message_id)<3){await conn.rollback();return{ok:false as const,reason:"POST_ALREADY_HAS_TEASER" as TeaserInsertReason};}
  // Rank candidates by pacing before applying channel-specific targeting. Campaigns
  // behind their scheduled delivery lead; the least recently placed campaign wins
  // the next tie, and CPM is only the final commercial tie-breaker.
  const [campaigns]=await conn.query<Campaign[]>(`SELECT c.*,u.ad_balance,COALESCE((SELECT MAX(tp.id) FROM teaser_placements tp WHERE tp.campaign_id=c.id),0) teaser_last_placement_id FROM campaigns c JOIN users u ON u.id=c.user_id WHERE c.teaser_enabled=1 AND c.type='views' AND c.status='active' AND (? IS NULL OR c.id=?) AND (c.start_at IS NULL OR c.start_at<=UTC_TIMESTAMP()) AND (c.end_at IS NULL OR c.end_at>UTC_TIMESTAMP()) ORDER BY CASE WHEN c.end_at IS NOT NULL AND c.end_at<=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 24 HOUR) THEN 0 ELSE 1 END,(GREATEST(c.total_budget-c.budget,0)/NULLIF(GREATEST(c.total_budget,c.budget),0))/GREATEST(0.01,CASE WHEN c.start_at IS NOT NULL AND c.end_at IS NOT NULL AND c.end_at>c.start_at THEN LEAST(1,GREATEST(0,TIMESTAMPDIFF(SECOND,c.start_at,UTC_TIMESTAMP())/NULLIF(TIMESTAMPDIFF(SECOND,c.start_at,c.end_at),0))) ELSE 1 END),teaser_last_placement_id ASC,c.teaser_cpm DESC,c.id ASC LIMIT 500 FOR UPDATE`,[input.campaignId??null,input.campaignId??null]);const exclusions=await loadCampaignExclusions(conn,"campaign",campaigns.map(c=>Number(c.id)),"channel");const campaign=campaigns.find(c=>Number(c.user_id)!==Number(ch.user_id)&&Number(c.budget)>=Number(c.teaser_cpm)/1000&&Number(c.ad_balance)>=Number(c.teaser_cpm)/1000&&!campaignExcludesChannel(exclusions,Number(c.id),ch)&&channelCampaignMatchesInventory({campaignCategory:c.category,campaignAudience:c.continents,channelCategories:ch.categories,channelAudience:ch.audience_continents,campaignCountries:c.countries,campaignLanguages:c.languages,channelCountry:ch.authoritative_country_code,channelLanguage:ch.authoritative_language_code}));
  if(!campaign){await conn.rollback();return{ok:false as const,reason:campaigns.length?"TARGETING_MISMATCH":"NO_CAMPAIGN" as TeaserInsertReason};}
  const [creatives]=await conn.query<Array<RowDataPacket&{id:number;copy_text:string}>>("SELECT id,copy_text FROM teaser_creatives WHERE campaign_id=? AND active=1 ORDER BY position LIMIT 1",[campaign.id]);const creative=creatives[0];if(!creative){await conn.rollback();return{ok:false as const,reason:"NO_CAMPAIGN" as TeaserInsertReason};}
  const organicEntities=parseEntities(input.snapshot.message_type==="text"?input.snapshot.entities:input.snapshot.caption_entities),token=opaqueTeaserToken(),suffix=renderTeaserSuffix(creative.copy_text,campaign.teaser_cta_key,`${origin()}/api/teaser/click/${token}`),rendered=appendTelegramEntities(input.snapshot.organic_text,organicEntities,suffix);if(!teaserContentFits(input.snapshot.message_type,rendered.text)){await conn.rollback();return{ok:false as const,reason:"POST_TOO_LONG" as TeaserInsertReason};}
  const [insert]=await conn.query<ResultSetHeader>(`INSERT IGNORE INTO teaser_placements(source_update_id,campaign_id,channel_id,publisher_id,teaser_creative_id,telegram_chat_id,telegram_message_id,message_type,creative_snapshot,cta_key,teaser_cpm_snapshot,tracking_token,organic_text,organic_entities,organic_post_id,emergency_job_id,rendered_suffix,rendered_entities,rendered_content_hash,status,operation_kind,operation_started_at,operation_lease_expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'inserting','insert',NOW(),DATE_ADD(NOW(),INTERVAL ${LEASE_SECONDS} SECOND))`,[input.sourceUpdateId,campaign.id,ch.id,ch.user_id,creative.id,input.snapshot.telegram_chat_id,input.snapshot.telegram_message_id,input.snapshot.message_type,creative.copy_text,campaign.teaser_cta_key,campaign.teaser_cpm,token,input.snapshot.organic_text,JSON.stringify(organicEntities),input.snapshot.id,input.emergencyJobId??null,suffix.text,JSON.stringify(rendered.entities),contentHash(rendered.text,rendered.entities)]);
  if(insert.affectedRows!==1){await conn.rollback();return{ok:false as const,reason:"DUPLICATE_PLACEMENT" as TeaserInsertReason};}
  const placementId=Number(insert.insertId);await conn.commit();committed=true;
  // Deliberately outside the committed transaction.
  const edit=await editTelegramTeaser({chatId:input.snapshot.telegram_chat_id,messageId:input.snapshot.telegram_message_id,messageType:input.snapshot.message_type,text:rendered.text,entities:rendered.entities});
  if(!edit.ok){if(edit.category==="CHANNEL_PERMISSION")await pool.query("UPDATE channels SET teaser_status='needs_permission' WHERE id=?",[ch.id]);const attempts=1;if(edit.terminal||teaserRetryExhausted(attempts))await pool.query("UPDATE teaser_placements SET status='failed',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,insertion_attempts=insertion_attempts+1,insertion_next_retry_at=NULL,last_error_code=?,last_error_category=? WHERE id=? AND status='inserting'",[edit.code,edit.category,placementId]);else await pool.query("UPDATE teaser_placements SET status='claimed',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,insertion_attempts=insertion_attempts+1,insertion_next_retry_at=DATE_ADD(NOW(),INTERVAL ? SECOND),last_error_code=?,last_error_category=? WHERE id=? AND status='inserting'",[teaserRetryDelaySeconds(attempts,edit.retryAfter),edit.code,edit.category,placementId]);const snapshotReason=edit.category==="CONTENT_TERMINAL"?"POST_TOO_LONG":["SNAPSHOT_MESSAGE_ABSENT","SNAPSHOT_NOT_EDITABLE","SNAPSHOT_TERMINAL_TELEGRAM"].includes(edit.code)?edit.code:null;return{ok:false as const,reason:(snapshotReason||(edit.terminal?"TELEGRAM_TERMINAL":"TELEGRAM_RETRYABLE")) as TeaserInsertReason,placementId,retryAfter:edit.retryAfter,errorCategory:edit.category};}
  const baseline=await fetchTeaserViews({chatId:input.snapshot.telegram_chat_id,messageId:input.snapshot.telegram_message_id,username:ch.username,channelType:ch.channel_type,trackingAccount:ch.tracking_account,rotationSeed:placementId});
  await pool.query("UPDATE teaser_placements SET status=?,operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,baseline_views=?,last_seen_views=?,inserted_at=COALESCE(inserted_at,NOW()),expires_at=DATE_ADD(NOW(),INTERVAL 24 HOUR),last_error_code=NULL,last_error_category=NULL,insertion_next_retry_at=NULL WHERE id=? AND status='inserting'",[baseline.ok?"active":"awaiting_baseline",baseline.ok?baseline.views:null,baseline.ok?baseline.views:null,placementId]);await pool.query("UPDATE channels SET teaser_last_placement_message_id=? WHERE id=?",[input.snapshot.telegram_message_id,ch.id]);return{ok:true as const,placementId};
 }catch(error){if(!committed)await conn.rollback().catch(()=>undefined);throw error;}finally{conn.release();}
}
