import { NextRequest, NextResponse } from "next/server";
import type { ResultSetHeader,RowDataPacket } from "mysql2/promise";
import pool from "@/lib/db";
import { acquireCronLock,releaseCronLock,requireCronSecret } from "@/lib/cronSecurity";
import { contentHash,editTelegramTeaser,fetchTeaserViews,settleTeaserViews,stripExactTeaserSuffix,teaserRetryDelaySeconds,teaserRetryExhausted,type TeaserCtaKey,type TelegramEntity } from "@/lib/teaser";
import { processTeaserEmergencyJobs } from "@/lib/teaserEmergency";

const BATCH=25, RECONCILIATION_BATCH=10, LEASE_SECONDS=120;
type Work=RowDataPacket&{id:number;campaign_id:number;channel_id:number;status:string;telegram_chat_id:number;telegram_message_id:number;message_type:string;organic_text:string;organic_entities:unknown;rendered_suffix:string;rendered_entities:unknown;rendered_content_hash:string;creative_snapshot:string;cta_key:TeaserCtaKey;tracking_token:string;baseline_views:number|null;expires_at:Date|null;removal_attempts:number;insertion_attempts:number;processing_attempts:number;processing_next_retry_at:Date|null;username:string|null;channel_type:string|null;tracking_account:number|null;campaign_status:string;campaign_teaser_enabled:number;channel_teaser_enabled:number;channel_teaser_status:string};
function entities(value:unknown):TelegramEntity[]{if(Array.isArray(value))return value as TelegramEntity[];if(typeof value==="string")try{return JSON.parse(value) as TelegramEntity[];}catch{return [];}return [];}
async function views(row:Work){return fetchTeaserViews({chatId:Number(row.telegram_chat_id),messageId:Number(row.telegram_message_id),username:row.username,channelType:row.channel_type,trackingAccount:row.tracking_account,rotationSeed:Number(row.id)});}
function missingTelegramMessage(result:{ok:boolean;code?:string}){return !result.ok&&["message_id_invalid","message_not_found","message_to_edit_not_found"].includes(String(result.code||"").toLowerCase());}
function placementStillAllowed(row:Work){return row.campaign_status==="active"&&Number(row.campaign_teaser_enabled)===1&&Number(row.channel_teaser_enabled)===1&&row.channel_teaser_status==="active";}
async function settle(row:Work,current:number){const conn=await pool.getConnection();try{await conn.beginTransaction();const result=await settleTeaserViews(conn,Number(row.id),current);if(!result.ok&&["CAMPAIGN_BUDGET_EXHAUSTED","INSUFFICIENT_AD_BALANCE"].includes(String(result.reason)))await conn.query("UPDATE teaser_placements SET status='removal_pending',removal_requested_at=COALESCE(removal_requested_at,NOW()),removal_reason=? WHERE id=?",[String(result.reason).toLowerCase(),row.id]);await conn.commit();return result;}catch(error){await conn.rollback();throw error;}finally{conn.release();}}
async function claimInsert(row:Work){const [claim]=await pool.query<ResultSetHeader>("UPDATE teaser_placements SET status='inserting',operation_kind='insert',operation_started_at=NOW(),operation_lease_expires_at=DATE_ADD(NOW(),INTERVAL ? SECOND) WHERE id=? AND (status='claimed' OR (status='inserting' AND operation_lease_expires_at<=NOW()))",[LEASE_SECONDS,row.id]);return Number(claim.affectedRows)===1;}
async function claimRemoval(row:Work){const [claim]=await pool.query<ResultSetHeader>("UPDATE teaser_placements SET status='removing',operation_kind='remove',operation_started_at=NOW(),operation_lease_expires_at=DATE_ADD(NOW(),INTERVAL ? SECOND) WHERE id=? AND (status='removal_pending' OR (status='removing' AND operation_lease_expires_at<=NOW()))",[LEASE_SECONDS,row.id]);return Number(claim.affectedRows)===1;}
async function finalizeInsert(row:Work){const baseline=await views(row);await pool.query("UPDATE teaser_placements SET status=?,operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,baseline_views=?,last_seen_views=?,inserted_at=COALESCE(inserted_at,NOW()),expires_at=COALESCE(expires_at,DATE_ADD(NOW(),INTERVAL 24 HOUR)),last_error_code=?,last_error_category=NULL,insertion_next_retry_at=NULL WHERE id=? AND status='inserting'",[baseline.ok?"active":"awaiting_baseline",baseline.ok?baseline.views:null,baseline.ok?baseline.views:null,baseline.ok?null:baseline.code,row.id]);await pool.query("UPDATE channels SET teaser_last_placement_message_id=? WHERE id=?",[row.telegram_message_id,row.channel_id]);return baseline.ok?"inserted":"awaiting_baseline";}
async function reconcileInsert(row:Work){if(!placementStillAllowed(row)){await pool.query("UPDATE teaser_placements SET status='removal_pending',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,removal_requested_at=COALESCE(removal_requested_at,NOW()),removal_reason='orphan_lifecycle_inactive' WHERE id=? AND status='inserting'",[row.id]);return"insert_cleanup";}
 if(!(await claimInsert(row)))return"insert_owned";
 const rendered={text:`${String(row.organic_text)}${String(row.rendered_suffix||"")}`,entities:entities(row.rendered_entities)};
 // The target is the complete persisted render, never an append to current Telegram content.
 const expectedText=rendered.text, expectedEntities=entities(row.rendered_entities);if(contentHash(expectedText,expectedEntities)!==String(row.rendered_content_hash)){await pool.query("UPDATE teaser_placements SET status='failed',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,last_error_code='RENDER_IDENTITY_MISMATCH' WHERE id=? AND status='inserting'",[row.id]);return"insert_failed";}
 const edit=await editTelegramTeaser({chatId:Number(row.telegram_chat_id),messageId:Number(row.telegram_message_id),messageType:row.message_type,text:expectedText,entities:expectedEntities});
 if(edit.ok)return finalizeInsert(row);
 if(edit.category==="CHANNEL_PERMISSION")await pool.query("UPDATE channels SET teaser_status='needs_permission' WHERE id=?",[row.channel_id]);
 if(edit.terminal){await pool.query("UPDATE teaser_placements SET status='failed',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,last_error_code=?,last_error_category=? WHERE id=? AND status='inserting'",[edit.code,edit.category,row.id]);return"insert_failed";}
 const attempt=Number(row.insertion_attempts||0)+1;if(teaserRetryExhausted(attempt)){await pool.query("UPDATE teaser_placements SET status='failed',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,insertion_attempts=?,insertion_next_retry_at=NULL,last_error_code=?,last_error_category=? WHERE id=? AND status='inserting'",[attempt,edit.code,edit.category,row.id]);return"insert_failed";}await pool.query("UPDATE teaser_placements SET status='claimed',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,insertion_attempts=?,insertion_next_retry_at=DATE_ADD(NOW(),INTERVAL ? SECOND),last_error_code=?,last_error_category=? WHERE id=? AND status='inserting'",[attempt,teaserRetryDelaySeconds(attempt,edit.retryAfter),edit.code,edit.category,row.id]);return"insert_retry";
}
async function reconcileRemoval(row:Work){if(!(await claimRemoval(row)))return"removal_owned";
 if(row.baseline_views!==null){const current=await views(row);if(current.ok)await settle(row,current.views);else if(missingTelegramMessage(current)){await pool.query("UPDATE teaser_placements SET status='already_absent',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,removed_at=COALESCE(removed_at,NOW()),last_error_code=? WHERE id=? AND status='removing'",[current.code,row.id]);return"absent";}}
 const [latestRows]=await pool.query<Array<RowDataPacket&{organic_text:string;entities:unknown;caption_entities:unknown;message_type:string}>>("SELECT organic_text,entities,caption_entities,message_type FROM channel_organic_posts WHERE channel_id=? AND telegram_message_id=? AND telegram_chat_id=? AND availability='available' ORDER BY last_seen_update_id DESC LIMIT 1",[row.channel_id,row.telegram_message_id,row.telegram_chat_id]);const latest=latestRows[0];
 // Placement snapshots are durable and remain a safe removal fallback even after
 // the rolling organic-post snapshot window has evicted an older Telegram post.
 const messageType=latest?.message_type||row.message_type;
 const latestEntities=latest?entities(messageType==="text"?latest.entities:latest.caption_entities):entities(row.organic_entities);
 const latestOrganic=stripExactTeaserSuffix(String(latest?.organic_text??row.organic_text??""),String(row.rendered_suffix||""));
 const result=await editTelegramTeaser({chatId:Number(row.telegram_chat_id),messageId:Number(row.telegram_message_id),messageType,text:latestOrganic,entities:latestEntities});
 if(result.ok){await pool.query("UPDATE teaser_placements SET status='removed',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,removed_at=COALESCE(removed_at,NOW()),last_error_code=NULL,last_error_category=NULL WHERE id=? AND status='removing'",[row.id]);return"removed";}
 if(result.category==="MESSAGE_TERMINAL"){await pool.query("UPDATE teaser_placements SET status='already_absent',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,removed_at=COALESCE(removed_at,NOW()),last_error_code=?,last_error_category=? WHERE id=? AND status='removing'",[result.code,result.category,row.id]);return"absent";}
 const attempts=Number(row.removal_attempts||0)+1;if(teaserRetryExhausted(attempts)){await pool.query("UPDATE teaser_placements SET status='failed',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,removal_attempts=?,removal_next_retry_at=NULL,last_error_code=?,last_error_category=? WHERE id=? AND status='removing'",[attempts,result.code,result.category,row.id]);return"removal_failed";}const delay=teaserRetryDelaySeconds(attempts,result.retryAfter);await pool.query("UPDATE teaser_placements SET status='removal_pending',operation_kind=NULL,operation_started_at=NULL,operation_lease_expires_at=NULL,removal_attempts=?,removal_next_retry_at=DATE_ADD(NOW(),INTERVAL ? SECOND),last_error_code=?,last_error_category=? WHERE id=? AND status='removing'",[attempts,delay,result.code,result.category,row.id]);return"removal_retry";
}
async function deferViewRetry(row:Work,stage:"baseline"|"view",code:string){const attempt=Number(row.processing_attempts||0)+1;if(teaserRetryExhausted(attempt)){await pool.query("UPDATE teaser_placements SET status='failed',processing_attempts=?,processing_next_retry_at=NULL,last_error_code=?,last_error_category='RETRY_CEILING' WHERE id=?",[attempt,code,row.id]);return`${stage}_failed`;}await pool.query("UPDATE teaser_placements SET processing_attempts=?,processing_next_retry_at=DATE_ADD(NOW(),INTERVAL ? SECOND),last_error_code=?,last_error_category='RETRYABLE_NETWORK' WHERE id=?",[attempt,teaserRetryDelaySeconds(attempt),code,row.id]);return`${stage}_retry`;}
async function processPlacement(row:Work){if(row.status==="claimed"||row.status==="inserting")return reconcileInsert(row);if(row.status==="awaiting_baseline"){const baseline=await views(row);if(!baseline.ok){if(missingTelegramMessage(baseline)){await pool.query("UPDATE teaser_placements SET status='already_absent',removed_at=COALESCE(removed_at,NOW()),last_error_code=? WHERE id=?",[baseline.code,row.id]);return"absent";}return deferViewRetry(row,"baseline",String(baseline.code||"VIEW_UNAVAILABLE"));}await pool.query("UPDATE teaser_placements SET baseline_views=?,last_seen_views=?,status='active',processing_attempts=0,processing_next_retry_at=NULL,last_error_code=NULL,last_error_category=NULL WHERE id=? AND status='awaiting_baseline'",[baseline.views,baseline.views,row.id]);return"baseline";}if(row.status==="active"){const current=await views(row);if(current.ok){await settle(row,current.views);await pool.query("UPDATE teaser_placements SET processing_attempts=0,processing_next_retry_at=NULL,last_error_category=NULL WHERE id=? AND status='active'",[row.id]);}else if(missingTelegramMessage(current)){await pool.query("UPDATE teaser_placements SET status='already_absent',removed_at=COALESCE(removed_at,NOW()),last_error_code=? WHERE id=?",[current.code,row.id]);return"absent";}else return deferViewRetry(row,"view",String(current.code||"VIEW_UNAVAILABLE"));if(row.expires_at&&new Date(row.expires_at).getTime()<=Date.now())await pool.query("UPDATE teaser_placements SET status='removal_pending',removal_requested_at=COALESCE(removal_requested_at,NOW()),removal_reason='expired' WHERE id=? AND status='active'",[row.id]);return"settled";}if(row.status==="removal_pending"||row.status==="removing")return reconcileRemoval(row);return"ignored";}
type PermissionChannel=RowDataPacket&{id:number;chat_id:string|number;teaser_status:string};
async function refreshTeaserPermissions(){
 const token=String(process.env.BOT_TOKEN||"");if(!token)return{checked:0,active:0,needs_permission:0,unavailable:0};
 const meResponse=await fetch(`https://api.telegram.org/bot${token}/getMe`,{signal:AbortSignal.timeout(8_000),cache:"no-store"}).catch(()=>null);
 const meBody=meResponse?await meResponse.json().catch(()=>null) as {ok?:boolean;result?:{id?:number}}|null:null;
 const botId=Number(meBody?.result?.id||0);if(!meResponse?.ok||!meBody?.ok||!botId)return{checked:0,active:0,needs_permission:0,unavailable:1};
 const [channels]=await pool.query<PermissionChannel[]>(`SELECT id,chat_id,teaser_status FROM channels WHERE status='active' AND is_deleted=FALSE AND teaser_enabled=1 AND (teaser_permission_checked_at IS NULL OR teaser_permission_checked_at<UTC_TIMESTAMP()-INTERVAL 24 HOUR) ORDER BY COALESCE(teaser_permission_checked_at,'1970-01-01'),id LIMIT 10`);
 const counts={checked:0,active:0,needs_permission:0,unavailable:0};
 for(const channel of channels){
  try{
   const response=await fetch(`https://api.telegram.org/bot${token}/getChatMember`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:channel.chat_id,user_id:botId}),signal:AbortSignal.timeout(8_000),cache:"no-store"});
   const body=await response.json().catch(()=>null) as {ok?:boolean;result?:{status?:string;can_edit_messages?:boolean}}|null;
   if(response.status===429||response.status>=500){counts.unavailable++;await pool.query("UPDATE channels SET teaser_permission_checked_at=UTC_TIMESTAMP()-INTERVAL 23 HOUR WHERE id=?",[channel.id]);continue;}
   const canEdit=Boolean(body?.ok&&(body.result?.status==="creator"||(body.result?.status==="administrator"&&body.result.can_edit_messages===true)));
   const status=canEdit?"active":"needs_permission";await pool.query("UPDATE channels SET teaser_status=?,teaser_permission_checked_at=UTC_TIMESTAMP() WHERE id=? AND status='active' AND teaser_enabled=1",[status,channel.id]);
   if(!canEdit)await pool.query("UPDATE teaser_placements SET status='removal_pending',removal_requested_at=COALESCE(removal_requested_at,UTC_TIMESTAMP()),removal_reason='permission_lost' WHERE channel_id=? AND status IN ('active','awaiting_baseline')",[channel.id]);
   counts.checked++;counts[status]++;
  }catch{counts.unavailable++;await pool.query("UPDATE channels SET teaser_permission_checked_at=UTC_TIMESTAMP()-INTERVAL 23 HOUR WHERE id=?",[channel.id]);}
 }
 return counts;
}
async function processRollout(){const token=String(process.env.BOT_TOKEN||"");if(!token)return{sent:0,failed:0};const [rows]=await pool.query<Array<RowDataPacket&{publisher_id:number;telegram_id:string|number;attempts:number}>>(`SELECT n.publisher_id,u.telegram_id,n.attempts FROM teaser_rollout_notifications n JOIN users u ON u.id=n.publisher_id WHERE n.status IN ('pending','failed') AND (n.next_retry_at IS NULL OR n.next_retry_at<=NOW()) ORDER BY n.publisher_id LIMIT 10`);let sent=0,failed=0;for(const row of rows){try{const response=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:row.telegram_id,text:"Teaser Ads are now live 🚀\n\nTeaser Ads have been enabled for your eligible monetized channels. Ads Galaxy can now add short sponsored ads to your regular posts to help increase your earnings.\n\nYou can adjust the daily limit or turn Teaser off from Channel settings. Channels without Edit Messages permission will need that permission before Teaser can start.",reply_markup:{inline_keyboard:[[{text:"Manage Channels",web_app:{url:"https://app.adsgalaxy.online/publisher/monetize"}}]]}}),signal:AbortSignal.timeout(10_000)});const body=await response.json().catch(()=>({})) as {ok?:boolean;parameters?:{retry_after?:number}};if(response.ok&&body.ok){await pool.query("UPDATE teaser_rollout_notifications SET status='sent',sent_at=NOW(),last_error_code=NULL WHERE publisher_id=?",[row.publisher_id]);sent++;}else{const attempt=Number(row.attempts)+1,delay=teaserRetryDelaySeconds(attempt,Number(body.parameters?.retry_after)||undefined);await pool.query("UPDATE teaser_rollout_notifications SET status='failed',attempts=?,next_retry_at=DATE_ADD(NOW(),INTERVAL ? SECOND),last_error_code=? WHERE publisher_id=?",[attempt,delay,response.status===429?"TELEGRAM_RATE_LIMIT":"TELEGRAM_SEND_FAILED",row.publisher_id]);failed++;}}catch{const attempt=Number(row.attempts)+1;await pool.query("UPDATE teaser_rollout_notifications SET status='failed',attempts=?,next_retry_at=DATE_ADD(NOW(),INTERVAL ? SECOND),last_error_code='TELEGRAM_NETWORK_ERROR' WHERE publisher_id=?",[attempt,teaserRetryDelaySeconds(attempt),row.publisher_id]);failed++;}}return{sent,failed};}
export async function GET(request:NextRequest){const denied=requireCronSecret(request);if(denied)return denied;const lock=await acquireCronLock("teaser-worker",240);if(!lock)return NextResponse.json({ok:true,skipped:"locked"});try{const emergency=await processTeaserEmergencyJobs();await pool.query(`UPDATE teaser_placements tp JOIN campaigns c ON c.id=tp.campaign_id JOIN users u ON u.id=c.user_id SET tp.status='removal_pending',tp.removal_requested_at=COALESCE(tp.removal_requested_at,NOW()),tp.removal_reason=CASE WHEN c.status<>'active' THEN 'campaign_inactive' WHEN c.budget<ROUND(tp.teaser_cpm_snapshot/1000,8) THEN 'campaign_budget_exhausted' ELSE 'insufficient_ad_balance' END WHERE tp.status IN ('active','awaiting_baseline') AND (c.status<>'active' OR c.teaser_enabled=0 OR c.budget<ROUND(tp.teaser_cpm_snapshot/1000,8) OR u.ad_balance<ROUND(tp.teaser_cpm_snapshot/1000,8))`);
 const [rows]=await pool.query<Work[]>(`SELECT tp.*,ch.username,ch.channel_type,ch.tracking_account,c.status campaign_status,c.teaser_enabled campaign_teaser_enabled,ch.teaser_enabled channel_teaser_enabled,ch.teaser_status channel_teaser_status FROM teaser_placements tp JOIN channels ch ON ch.id=tp.channel_id JOIN campaigns c ON c.id=tp.campaign_id WHERE ((tp.status='claimed' AND (tp.insertion_next_retry_at IS NULL OR tp.insertion_next_retry_at<=NOW())) OR (tp.status='inserting' AND tp.operation_lease_expires_at<=NOW()) OR tp.status IN ('active','awaiting_baseline') OR (tp.status='removal_pending' AND (tp.removal_next_retry_at IS NULL OR tp.removal_next_retry_at<=NOW())) OR (tp.status='removing' AND tp.operation_lease_expires_at<=NOW())) ORDER BY CASE tp.status WHEN 'removing' THEN 0 WHEN 'removal_pending' THEN 1 WHEN 'inserting' THEN 2 WHEN 'awaiting_baseline' THEN 3 WHEN 'claimed' THEN 4 ELSE 5 END,tp.id LIMIT ${BATCH}`);const counts:Record<string,number>={};for(const row of rows){try{const result=await processPlacement(row);counts[result]=(counts[result]||0)+1;}catch(error){console.error("teaser orphan reconciliation failed",{placementId:row.id,campaignId:row.campaign_id,channelId:row.channel_id,messageId:row.telegram_message_id,operation:row.status,errorCategory:error instanceof Error?error.name:"unknown"});counts.failed=(counts.failed||0)+1;}}const permissions=await refreshTeaserPermissions();const rollout=await processRollout();return NextResponse.json({ok:true,processed:rows.length,reconciliationLimit:RECONCILIATION_BATCH,counts,permissions,rollout,emergency});}finally{await releaseCronLock(lock);}}
