import assert from "node:assert/strict";import{execFileSync}from"node:child_process";import{readFileSync}from"node:fs";import test from"node:test";
const client=process.env.MARIADB_TEST_CLIENT,password=process.env.MARIADB_TEST_PASSWORD,port=process.env.MARIADB_TEST_PORT||"3407",migration=readFileSync("db/migrations/20260802_0110_channel_refresh_release_safeguards.sql","utf8");const sql=(db,input)=>execFileSync(client,["--host=127.0.0.1",`--port=${port}`,"--user=root",`--password=${password}`,...(db?[db]:[]),"--batch","--skip-column-names"],{input,encoding:"utf8"}).trim();
test("MariaDB 11.4 migration is rerunnable and protects existing reversals",{skip:!client||!password},()=>{sql(null,"DROP DATABASE IF EXISTS agx_channel_refresh;CREATE DATABASE agx_channel_refresh;");sql("agx_channel_refresh",`CREATE TABLE users(id INT NOT NULL PRIMARY KEY);CREATE TABLE referrals(id INT NOT NULL PRIMARY KEY);CREATE TABLE referral_reward_ledger(id BIGINT UNSIGNED NOT NULL PRIMARY KEY);CREATE TABLE referral_reward_reversals(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,idempotency_key VARCHAR(191) NOT NULL UNIQUE,user_id BIGINT UNSIGNED NOT NULL,referral_id BIGINT UNSIGNED NOT NULL,original_reward_id BIGINT UNSIGNED NOT NULL UNIQUE,amount DECIMAL(20,8) NOT NULL,currency CHAR(4) NOT NULL,reason VARCHAR(255) NOT NULL,old_balance DECIMAL(20,8) NOT NULL,new_balance DECIMAL(20,8) NOT NULL,actor VARCHAR(64) NOT NULL,created_at DATETIME(6) NOT NULL);CREATE TABLE channels(id INT PRIMARY KEY);INSERT INTO users VALUES(1);INSERT INTO referrals VALUES(2);INSERT INTO referral_reward_ledger VALUES(3),(4),(5);INSERT INTO referral_reward_reversals VALUES(NULL,'k',1,2,3,.005,'USDT','r',1,.995,'system',NOW(6));`);sql("agx_channel_refresh",migration);sql("agx_channel_refresh",migration);assert.equal(sql("agx_channel_refresh","SELECT COUNT(*) FROM referral_reward_reversals;"),"1");assert.equal(sql("agx_channel_refresh","SELECT COUNT(*) FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='referral_reward_reversals';"),"3");const insert=(key,user,ref,reward)=>`INSERT INTO referral_reward_reversals(idempotency_key,user_id,referral_id,original_reward_id,amount,currency,reason,old_balance,new_balance,actor,created_at)VALUES('${key}',${user},${ref},${reward},.1,'USDT','r',1,.9,'x',NOW(6));`;assert.throws(()=>sql("agx_channel_refresh",insert("bad-user",99,2,4)));assert.throws(()=>sql("agx_channel_refresh",insert("bad-ref",1,99,5)));assert.throws(()=>sql("agx_channel_refresh",insert("bad-reward",1,2,999)));});

const partialStates=[
  ["columns without indexes","ALTER TABLE channels ADD subscribers_next_retry_at DATETIME NULL,ADD below_minimum_review_required TINYINT(1) NOT NULL DEFAULT 0,ADD below_minimum_review_required_at DATETIME NULL"],
  ["retry column without scheduler index","ALTER TABLE channels ADD subscribers_next_retry_at DATETIME NULL"],
  ["partial seven-day columns","ALTER TABLE channels ADD below_minimum_review_required TINYINT(1) NOT NULL DEFAULT 0"],
  ["tracking table missing index and primary key","CREATE TABLE telegram_tracking_account_health(account_key VARCHAR(32) NOT NULL,status VARCHAR(16) NOT NULL) ENGINE=InnoDB"],
  ["one reversal foreign key exists","ALTER TABLE referral_reward_reversals MODIFY user_id INT NOT NULL,MODIFY referral_id INT NOT NULL,ADD CONSTRAINT fk_referral_reward_reversal_user FOREIGN KEY(user_id) REFERENCES users(id)"],
  ["interrupted after first channel DDL block","ALTER TABLE channels ADD subscribers_next_retry_at DATETIME NULL,ADD below_minimum_review_required TINYINT(1) NOT NULL DEFAULT 0,ADD below_minimum_review_required_at DATETIME NULL,ADD KEY idx_channels_subscriber_retry(subscribers_next_retry_at,id)"],
];
for(const [name,partial] of partialStates)test(`partial migration recovery: ${name}`,{skip:!client||!password},()=>{const db=`agx_partial_${partialStates.findIndex(v=>v[0]===name)}`;sql(null,`DROP DATABASE IF EXISTS ${db};CREATE DATABASE ${db};`);sql(db,`CREATE TABLE users(id INT NOT NULL PRIMARY KEY);CREATE TABLE referrals(id INT NOT NULL PRIMARY KEY);CREATE TABLE referral_reward_ledger(id BIGINT UNSIGNED NOT NULL PRIMARY KEY);CREATE TABLE referral_reward_reversals(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,idempotency_key VARCHAR(191) UNIQUE,user_id BIGINT UNSIGNED NOT NULL,referral_id BIGINT UNSIGNED NOT NULL,original_reward_id BIGINT UNSIGNED NOT NULL UNIQUE,amount DECIMAL(20,8),currency CHAR(4),reason VARCHAR(255),old_balance DECIMAL(20,8),new_balance DECIMAL(20,8),actor VARCHAR(64));CREATE TABLE channels(id INT PRIMARY KEY);INSERT INTO users VALUES(1);INSERT INTO referrals VALUES(2);INSERT INTO referral_reward_ledger VALUES(3);INSERT INTO referral_reward_reversals VALUES(NULL,'seed',1,2,3,.1,'USDT','seed',1,.9,'test');${partial};`);sql(db,migration);sql(db,migration);assert.equal(sql(db,"SELECT COUNT(*) FROM referral_reward_reversals"),"1");assert.equal(sql(db,"SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='channels' AND INDEX_NAME='idx_channels_subscriber_retry'"),"2");assert.equal(sql(db,"SELECT COUNT(*) FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='referral_reward_reversals'"),"3");assert.match(sql(db,"SHOW CREATE TABLE telegram_tracking_account_health"),/PRIMARY KEY/);});
