import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";const read=(p)=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
test("GroupPilot client keeps credentials server-only and forwards required headers",()=>{const s=read("src/lib/groupPilot.ts");assert.match(s,/import "server-only"/);assert.match(s,/process\.env\.GROUPPILOT_KEY/);assert.match(s,/X-GroupPilot-Site/);assert.match(s,/Idempotency-Key/);assert.match(s,/AbortSignal\.timeout\(TIMEOUT_MS\)/);assert.doesNotMatch(s,/NEXT_PUBLIC_/)});
test("AI route authenticates and owns sessions server-side",()=>{const s=read("src/app/api/ai-support/route.ts");assert.match(s,/getAuthenticatedUserStatus/);assert.doesNotMatch(s,/body\.userId/);assert.match(s,/WHERE user_id = \?/);assert.match(s,/client_request_id/);assert.match(s,/groupPilotClearConversation/)});
test("safe upstream errors are mapped",()=>{const s=read("src/lib/groupPilot.ts");for(const x of ["RATE_LIMITED","DAILY_CAPACITY_REACHED","REQUEST_TOO_LARGE","INVALID_REQUEST","AI_TEMPORARILY_UNAVAILABLE"])assert.match(s,new RegExp(x))});
test("transient retry preserves the same upstream idempotency header",()=>{const s=read("src/lib/groupPilot.ts");assert.match(s,/for \(let attempt = 0; attempt < 2/);assert.equal((s.match(/headers\.set\("Idempotency-Key", idempotencyKey\)/g)||[]).length,1)});
test("idempotency key is a header only and never an upstream JSON field",()=>{const s=read("src/lib/groupPilot.ts");assert.match(s,/const payload = \{ sessionId: input\.sessionId, userId: input\.userId, message: input\.message \}/);assert.match(s,/JSON\.stringify\(payload\)/);assert.doesNotMatch(s,/JSON\.stringify\(input\)/)});
test("AI Support is last in both menus while FAQ remains",()=>{const s=read("src/components/layout/Sidebar.tsx");for(const role of ["publisher","advertiser"]){const faq=s.indexOf(`/${role}/faqs`),ai=s.indexOf(`/${role}/ai-support`);assert.ok(faq>=0&&ai>faq)}assert.equal((s.match(/navigation\.aiSupport/g)||[]).length,2)});
test("English and Russian support strings are complete",()=>{const en=read("src/i18n/en.ts"),ru=read("src/i18n/ru.ts");for(const key of ["title","subtitle","welcome","placeholder","send","responding","clear","clearConfirm","cancel","cleared","retry","empty","loading","error.generic","error.rateLimited","error.capacity","error.tooLarge","error.invalid"]){assert.ok(en.includes(`aiSupport.${key}`));assert.ok(ru.includes(`aiSupport.${key}`))}});
test("fast UI is optimistic and prevents duplicate submits",()=>{const s=read("src/components/shared/AiSupportPanel.tsx");assert.match(s,/setMessages\(\(current\).*role: "USER"/s);assert.match(s,/if \(!message \|\| sending\) return/);assert.match(s,/AbortController/);assert.match(s,/AI is responding|aiSupport\.responding/)});
