import assert from "node:assert/strict";
import test from "node:test";
import mysql, { type Connection } from "mysql2/promise";
import { rebuildReferralEarningsCache, settleInsertedReferralReward } from "../src/lib/paidReferralEarnings";

const port=Number(process.env.MARIADB_TEST_PORT||0),password=process.env.MARIADB_TEST_PASSWORD,enabled=Boolean(port&&password);
const open=()=>mysql.createConnection({host:"127.0.0.1",port,user:"root",password,multipleStatements:true});
async function reset(db:Connection){await db.query(`DROP DATABASE IF EXISTS agx_cache_writer;CREATE DATABASE agx_cache_writer;USE agx_cache_writer;
CREATE TABLE users(id INT PRIMARY KEY,balance_available DECIMAL(24,8) NOT NULL DEFAULT 0,total_referral_earnings DECIMAL(24,8) NULL DEFAULT 0);
CREATE TABLE referrals(id INT PRIMARY KEY,user_id INT,reward_status VARCHAR(30));
CREATE TABLE referral_reward_ledger(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,idempotency_key VARCHAR(191) UNIQUE,user_id INT NOT NULL,referral_id INT NULL,reward_type VARCHAR(40) NOT NULL,amount DECIMAL(18,8) NOT NULL,status VARCHAR(30) NOT NULL,settled_amount DECIMAL(18,8) NOT NULL DEFAULT 0,settled_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE audits(id BIGINT AUTO_INCREMENT PRIMARY KEY,event_key VARCHAR(191) UNIQUE,user_id INT);
INSERT INTO users VALUES(1,0,0);INSERT INTO referrals VALUES(10,2,'pending'),(11,3,'pending');`)}
async function use(db:Connection){await db.query("USE agx_cache_writer")}
async function credit(db:Connection,key:string,type="referral_join",amount="0.00500000",referralId=10,fail?:string){await db.beginTransaction();try{const [insert]:any=await db.query("INSERT IGNORE INTO referral_reward_ledger(idempotency_key,user_id,referral_id,reward_type,amount,status) VALUES(?,1,?,?,?,'pending')",[key,referralId,type,amount]);if(insert.affectedRows!==1){await db.commit();return false}const wrapped={query:async(sql:string,params?:unknown[])=>{if(fail&&sql.startsWith(fail))throw new Error("forced_failure");return db.query(sql,params as any)}};await settleInsertedReferralReward(wrapped,{ledgerId:Number(insert.insertId),userId:1,amount});if(fail==="UPDATE referrals")throw new Error("forced_failure");await db.query("UPDATE referrals SET reward_status='paid' WHERE id=?",[referralId]);if(fail==="INSERT INTO audits")throw new Error("forced_failure");await db.query("INSERT INTO audits(event_key,user_id) VALUES(?,1)",[key]);await db.commit();return true}catch(e){await db.rollback();throw e}}
async function state(db:Connection){const [[u]]:any=await db.query("SELECT balance_available,total_referral_earnings FROM users WHERE id=1");const [[l]]:any=await db.query("SELECT COUNT(*) n,COALESCE(SUM(CASE WHEN status='paid' THEN amount ELSE 0 END),0) paid FROM referral_reward_ledger");return{balance:String(u.balance_available),cache:String(u.total_referral_earnings),rows:Number(l.n),paid:String(l.paid)}}

test("registration: one and two exact 0.005 rewards; retry and old nominal are harmless",{skip:!enabled},async()=>{const db=await open();try{await reset(db);assert.equal(await credit(db,"join:10"),true);assert.deepEqual(await state(db),{balance:"0.00500000",cache:"0.00500000",rows:1,paid:"0.00500000"});assert.equal(await credit(db,"join:10","referral_join","0.01000000"),false);assert.equal(await credit(db,"join:11","referral_join","0.00500000",11),true);assert.deepEqual(await state(db),{balance:"0.01000000",cache:"0.01000000",rows:2,paid:"0.01000000"})}finally{await db.end()}});
test("verified, first bonus, milestone and sprint rewards are each counted once",{skip:!enabled},async()=>{const db=await open();try{await reset(db);for(const [k,t,a]of[["verified:10","verified_referral","0.01000000"],["bonus:1","first_referral_bonus","0.10000000"],["milestone:1","milestone_10","0.25000000"],["sprint:1","daily_sprint","0.50000000"]]){assert.equal(await credit(db,k,t,a),true);assert.equal(await credit(db,k,t,a),false)}assert.deepEqual(await state(db),{balance:"0.86000000",cache:"0.86000000",rows:4,paid:"0.86000000"})}finally{await db.end()}});
test("concurrent duplicate credits once; separate rewards both succeed",{skip:!enabled},async()=>{const seed=await open(),a=await open(),b=await open();try{await reset(seed);await use(a);await use(b);const same=await Promise.all([credit(a,"same"),credit(b,"same")]);assert.equal(same.filter(Boolean).length,1);const separate=await Promise.all([credit(a,"a"),credit(b,"b",undefined,undefined,11)]);assert.deepEqual(separate,[true,true]);assert.deepEqual(await state(seed),{balance:"0.01500000",cache:"0.01500000",rows:3,paid:"0.01500000"})}finally{await seed.end();await a.end();await b.end()}});
for(const failure of ["UPDATE referral_reward_ledger","UPDATE users SET balance","UPDATE users SET total_referral","UPDATE referrals","INSERT INTO audits"])test(`transaction rollback leaves no partial state after ${failure}`,{skip:!enabled},async()=>{const db=await open();try{await reset(db);await assert.rejects(()=>credit(db,"failure",undefined,undefined,undefined,failure),/forced_failure|referral_cache/);assert.deepEqual(await state(db),{balance:"0.00000000",cache:"0.00000000",rows:0,paid:"0.00000000"})}finally{await db.end()}});
test("canonical rebuild excludes reversed, pending, rejected and failed rows; zero is safe",{skip:!enabled},async()=>{const db=await open();try{await reset(db);await db.query("INSERT INTO referral_reward_ledger(idempotency_key,user_id,reward_type,amount,status) VALUES('paid',1,'bonus',.1,'paid'),('reversed',1,'bonus',.2,'reversed'),('pending',1,'bonus',.3,'pending'),('rejected',1,'bonus',.4,'rejected'),('failed',1,'bonus',.5,'failed')");await db.beginTransaction();assert.equal(await rebuildReferralEarningsCache(db,1),"0.10000000");await db.commit();assert.equal((await state(db)).cache,"0.10000000");await db.query("UPDATE referral_reward_ledger SET status='reversed' WHERE idempotency_key='paid'");await db.beginTransaction();assert.equal(await rebuildReferralEarningsCache(db,1),"0.00000000");await db.commit()}finally{await db.end()}});
test("large exact decimal totals retain eight-place precision",{skip:!enabled},async()=>{const db=await open();try{await reset(db);await db.query("INSERT INTO referral_reward_ledger(idempotency_key,user_id,reward_type,amount,status) VALUES('large',1,'bonus',9999999999.12345678,'paid'),('small',1,'bonus',.00000001,'paid')");await db.beginTransaction();assert.equal(await rebuildReferralEarningsCache(db,1),"9999999999.12345679");await db.commit()}finally{await db.end()}});
test("reversal and retry remove the original once; cache-only repair never debits balance",{skip:!enabled},async()=>{const db=await open();try{await reset(db);await credit(db,"join");await db.beginTransaction();const [r]:any=await db.query("UPDATE referral_reward_ledger SET status='reversed' WHERE idempotency_key='join' AND status='paid'");if(r.affectedRows)await db.query("UPDATE users SET balance_available=balance_available-.005 WHERE id=1");await rebuildReferralEarningsCache(db,1);await db.commit();const before=await state(db);await db.beginTransaction();const [retry]:any=await db.query("UPDATE referral_reward_ledger SET status='reversed' WHERE idempotency_key='join' AND status='paid'");assert.equal(retry.affectedRows,0);await rebuildReferralEarningsCache(db,1);await db.commit();assert.deepEqual(await state(db),before);await db.query("UPDATE users SET total_referral_earnings=9");await db.beginTransaction();await rebuildReferralEarningsCache(db,1);await db.commit();assert.equal((await state(db)).balance,"0.00000000") }finally{await db.end()}});
