import assert from "node:assert/strict";
import test from "node:test";
import mysql from "mysql2/promise";
import { reconcileInvalidReferralRewards } from "../src/lib/referralReconciliation";

const port=Number(process.env.MARIADB_TEST_PORT||0),password=process.env.MARIADB_TEST_PASSWORD;
async function connection(){return mysql.createConnection({host:"127.0.0.1",port,user:"root",password,multipleStatements:true});}
async function reset(conn:mysql.Connection){await conn.query("DROP DATABASE IF EXISTS agx_reconcile;CREATE DATABASE agx_reconcile;USE agx_reconcile");await conn.query(`
CREATE TABLE users(id INT PRIMARY KEY,username VARCHAR(64),balance_available DECIMAL(20,8),balance_locked DECIMAL(20,8),total_referral_earnings DECIMAL(20,8),total_withdrawn DECIMAL(20,8));
CREATE TABLE referrals(id INT PRIMARY KEY,status VARCHAR(32),reward_status VARCHAR(32));
CREATE TABLE referral_reward_ledger(id BIGINT UNSIGNED PRIMARY KEY,user_id INT,referral_id INT,reward_type VARCHAR(32),status VARCHAR(32),amount DECIMAL(20,8),reversal_reference VARCHAR(191));
CREATE TABLE referral_reward_reversals(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,idempotency_key VARCHAR(191) UNIQUE,user_id INT,referral_id INT,original_reward_id BIGINT UNSIGNED UNIQUE,amount DECIMAL(20,8),currency CHAR(4),reason VARCHAR(255),old_balance DECIMAL(20,8),new_balance DECIMAL(20,8),actor VARCHAR(64));
CREATE TABLE referral_reconciliation_audits(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,operation_key VARCHAR(191) UNIQUE,user_id INT,actor VARCHAR(64),reward_count INT,debit DECIMAL(20,8),metadata JSON,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
INSERT INTO users VALUES(78930,'Cade_Owner',5.96500000,13.06262324,5.46500000,0);
INSERT INTO referrals VALUES(10,'fraud','blocked');
INSERT INTO referral_reward_ledger VALUES(20,78930,10,'referral_join','paid',0.09500000,NULL);`);}

test("real transaction reverses once and repeat is an idempotent no-op",{skip:!port||!password},async()=>{const conn=await connection();try{await reset(conn);await conn.beginTransaction();const first=await reconcileInvalidReferralRewards(conn,78930,"Cade_Owner");await conn.commit();assert.equal(first.debit,"0.09500000");assert.equal(first.reversed,1);await conn.beginTransaction();const second=await reconcileInvalidReferralRewards(conn,78930,"Cade_Owner");await conn.rollback();assert.equal(second.debit,"0.00000000");assert.equal(second.reversed,0);const [[row]]:any=await conn.query("SELECT balance_available,total_referral_earnings,(SELECT COUNT(*) FROM referral_reward_reversals) reversals,(SELECT COUNT(*) FROM referral_reconciliation_audits) audits FROM users WHERE id=78930");assert.equal(String(row.balance_available),"5.87000000");assert.equal(String(row.total_referral_earnings),"0.00000000");assert.equal(row.reversals,1);assert.equal(row.audits,1);}finally{await conn.end();}});

test("two independent simultaneous transactions debit, reverse, rebuild and audit exactly once",{skip:!port||!password},async()=>{const first=await connection(),second=await connection();try{await reset(first);await second.query("USE agx_reconcile");await first.beginTransaction();await second.beginTransaction();const p1=reconcileInvalidReferralRewards(first,78930,"Cade_Owner");await new Promise(resolve=>setTimeout(resolve,25));const p2=reconcileInvalidReferralRewards(second,78930,"Cade_Owner");const r1=await p1;await first.commit();const r2=await p2;await second.commit();assert.equal(r1.debit,"0.09500000");assert.equal(r2.debit,"0.00000000");const [[row]]:any=await first.query("SELECT balance_available,total_referral_earnings,(SELECT COUNT(*) FROM referral_reward_reversals) reversals,(SELECT COUNT(*) FROM referral_reconciliation_audits) audits,(SELECT status FROM referral_reward_ledger WHERE id=20) reward_status FROM users WHERE id=78930");assert.equal(String(row.balance_available),"5.87000000");assert.equal(String(row.total_referral_earnings),"0.00000000");assert.equal(row.reversals,1);assert.equal(row.audits,1);assert.equal(row.reward_status,"reversed");}finally{await first.end();await second.end();}});

for(const [name,needle] of [["after reversal insert","INSERT INTO referral_reward_reversals"],["after reward update","UPDATE referral_reward_ledger"],["before audit insertion","INSERT INTO referral_reconciliation_audits"]] as const)test(`forced failure ${name} rolls back every table`,{skip:!port||!password},async()=>{const conn=await connection();try{await reset(conn);await conn.beginTransaction();let armed=false;const wrapped={query:async(sql:string,params?:unknown[])=>{if(armed||name==="before audit insertion"&&sql.startsWith(needle))throw new Error(`forced_${name}`);const result=await conn.query(sql,params as any);if(name!=="before audit insertion"&&sql.startsWith(needle))armed=true;return result as any;}};await assert.rejects(()=>reconcileInvalidReferralRewards(wrapped,78930,"Cade_Owner"),/forced_/);await conn.rollback();const [[row]]:any=await conn.query("SELECT balance_available,total_referral_earnings,(SELECT COUNT(*) FROM referral_reward_reversals) reversals,(SELECT COUNT(*) FROM referral_reconciliation_audits) audits,(SELECT status FROM referral_reward_ledger WHERE id=20) reward_status FROM users WHERE id=78930");assert.equal(String(row.balance_available),"5.96500000");assert.equal(String(row.total_referral_earnings),"5.46500000");assert.equal(row.reversals,0);assert.equal(row.audits,0);assert.equal(row.reward_status,"paid");}finally{await conn.end();}});

test("insufficient balance and mismatched idempotency roll back",{skip:!port||!password},async()=>{const conn=await connection();try{await reset(conn);await conn.query("UPDATE users SET balance_available=.01 WHERE id=78930");await conn.beginTransaction();await assert.rejects(()=>reconcileInvalidReferralRewards(conn,78930,"Cade_Owner"),/insufficient_available_balance/);await conn.rollback();const [statusRows]:any=await conn.query("SELECT status FROM referral_reward_ledger WHERE id=20");assert.equal(statusRows[0].status,"paid");await conn.query("UPDATE users SET balance_available=5.965 WHERE id=78930");await conn.query("INSERT INTO referral_reward_reversals(idempotency_key,user_id,referral_id,original_reward_id,amount,currency,reason,old_balance,new_balance,actor) VALUES('referral-invalid-reversal:20',78930,10,20,.05,'USDT','bad',1,.95,'test')");await conn.beginTransaction();await assert.rejects(()=>reconcileInvalidReferralRewards(conn,78930,"Cade_Owner"),/reversal_idempotency_mismatch/);await conn.rollback();const [balanceRows]:any=await conn.query("SELECT balance_available FROM users WHERE id=78930");assert.equal(String(balanceRows[0].balance_available),"5.96500000");}finally{await conn.end();}});

test("original already reversed performs cache-only correction without debit",{skip:!port||!password},async()=>{const conn=await connection();try{await reset(conn);await conn.query("UPDATE referral_reward_ledger SET status='reversed' WHERE id=20");await conn.beginTransaction();const result=await reconcileInvalidReferralRewards(conn,78930,"Cade_Owner");await conn.commit();assert.equal(result.debit,"0.00000000");assert.equal(result.reversed,0);assert.equal(result.referralTotal,"0.00000000");}finally{await conn.end();}});
