import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const read=(path)=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
const telegram=read("src/lib/teaser.ts");
const placement=read("src/lib/teaserPlacement.ts");
const emergency=read("src/lib/teaserEmergency.ts");
const campaign=read("src/app/api/advertiser/campaigns/[id]/route.ts");
const details=read("src/components/advertiser/CampaignDetailsScreen.tsx");
const wizard=read("src/app/advertiser/campaigns/new/[kind]/page.tsx");
const worker=read("src/app/api/cron/teaser/route.ts");
const en=read("src/i18n/en.ts"),ru=read("src/i18n/ru.ts");

test("deleted messages are snapshot-local terminal outcomes",()=>{assert.match(telegram,/message to edit not found/);assert.match(telegram,/SNAPSHOT_MESSAGE_ABSENT/);});
test("no-longer-editable messages are snapshot-local terminal outcomes",()=>{assert.match(telegram,/message can.t be edited/);assert.match(telegram,/SNAPSHOT_NOT_EDITABLE/);});
test("up to five distinct snapshots are attempted newest first",()=>{assert.match(emergency,/ORDER BY telegram_message_id DESC LIMIT 5/);assert.match(emergency,/attemptedSnapshotIds=new Set/);assert.match(emergency,/attemptedSnapshotIds\.has/);});
test("multiple snapshot-local failures may fall through to success",()=>{for(const reason of ["SNAPSHOT_MESSAGE_ABSENT","SNAPSHOT_NOT_EDITABLE","SNAPSHOT_TERMINAL_TELEGRAM"])assert.match(emergency,new RegExp(reason));assert.match(emergency,/if\(out\.ok\|\|!out\.reason\|\|!TEASER_SNAPSHOT_FALLBACK_REASONS\.has/);});
test("all snapshot-local failures exhaust to a safe skip",()=>{assert.match(emergency,/out=\{ok:false,reason:"NO_SAFE_ORGANIC_SNAPSHOT"\}/);assert.match(emergency,/"skipped"/);});
test("rate limits and network errors do not consume another snapshot",()=>{assert.doesNotMatch(emergency,/TEASER_SNAPSHOT_FALLBACK_REASONS[^;]+TELEGRAM_RETRYABLE/);assert.match(telegram,/TELEGRAM_RATE_LIMIT/);assert.match(telegram,/TELEGRAM_NETWORK_ERROR/);});
test("channel permission and lifecycle failures do not consume snapshots",()=>{for(const reason of ["EDIT_PERMISSION_MISSING","CAMPAIGN_INACTIVE","INSUFFICIENT_BALANCE"])assert.doesNotMatch(emergency,new RegExp(`TEASER_SNAPSHOT_FALLBACK_REASONS[^;]+${reason}`));});
test("fallback success records one injected channel outcome",()=>{assert.match(emergency,/if\(out\.ok\)await pool\.query\("UPDATE teaser_emergency_job_channels SET status='injected'/);});
test("failed snapshots cannot collide with the eventual placement",()=>{assert.match(placement,/INSERT IGNORE INTO teaser_placements/);assert.match(placement,/DUPLICATE_PLACEMENT/);});
test("combined Views campaign has explicit idempotent disable operation",()=>{assert.match(campaign,/action==="disable_teaser"/);assert.match(campaign,/teaser_mode!=="standard_plus_teaser"/);assert.match(campaign,/idempotent:true,standard_campaign_status:campaign\.status/);});
test("disable preserves standard campaign and queues active Teaser cleanup",()=>{const block=campaign.slice(campaign.indexOf('action==="disable_teaser"'),campaign.indexOf('action==="toggle_teaser"'));assert.doesNotMatch(block,/status\s*=\s*'paused'/);assert.match(block,/status='removal_pending'/);assert.doesNotMatch(block,/wallet|refund|budget\s*=/i);});
test("one-hour cooldown and eligible re-enable are server enforced",()=>{assert.match(campaign,/DATE_ADD\(NOW\(\),INTERVAL 1 HOUR\)/);assert.match(campaign,/TEASER_RESUME_COOLDOWN/);assert.match(campaign,/TEASER_RESUME_NOT_ELIGIBLE/);assert.match(campaign,/COUNT\(\*\) FROM teaser_creatives/);});
test("campaign details exposes confirmed localized disable action",()=>{assert.match(details,/action: "disable_teaser"/);assert.match(details,/teaser\.disableConfirmTitle/);assert.match(details,/teaser\.disableConfirmBody/);});
test("Teaser wizard uses localized labels, CTA values and safe validation mapping",()=>{for(const key of ["teaser.callToAction","teaser.copies","teaser.addAnother","teaser.sponsored","teaser.copyPlaceholder"])assert.match(wizard,new RegExp(key.replace(".","\\.")));assert.match(wizard,/safeTeaserError|teaserErrorMessageKey/);assert.doesNotMatch(wizard,/>Teaser Copies<|>Call to Action<|>\+ Add Another<|>Sponsored · Ads Galaxy</);});
test("Pass 5 locale keys have nonblank EN and RU values",()=>{for(const key of ["teaser.disableConfirmTitle","teaser.disableConfirmBody","teaser.copyValidation","teaser.cpmValidation","teaser.copyPlaceholder","teaser.pricing","teaser.revenueSplit","teaser.cta.learn_more","teaser.cta.visit_now"]){assert.match(en,new RegExp(`"${key.replaceAll(".","\\.")}":"[^"]+"`));assert.match(ru,new RegExp(`"${key.replaceAll(".","\\.")}":"[^"]+"`));}});
test("Teaser form uses CTA Button, Message Text, three-character names and Teaser CPM reach",()=>{assert.match(en,/"teaser\.callToAction":"CTA Button"/);assert.match(en,/"teaser\.copies":"Message Text"/);assert.match(wizard,/Minimum 3 characters required/);assert.match(wizard,/isTeaserOnly \? Number\(pricingValue\) : effectiveBid/);});
test("Teaser removal restores the durable organic snapshot",()=>{assert.match(worker,/latest\?\.organic_text\?\?row\.organic_text/);assert.match(worker,/result\.category==="MESSAGE_TERMINAL"/);});
