"use client";

import React from "react";
import { Check, Clock3, Copy, HelpCircle, Megaphone, ShieldCheck, Users, Wallet, X } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { apiFetch } from "@/lib/api";
import { useHeader } from "@/context/HeaderContext";

type CampaignData = {
  campaign: { status: string; starts_at: string | null; ends_at: string | null; wallet_edit_ends_at: string | null; payment_completed?: boolean };
  referral_link: string | null;
  wallet: { network: string; address: string } | null;
  wallet_editable: boolean;
  stats: Record<string, string | number | null>;
  tiers: Array<{ minimum: number; maximum: number; amount: string }>;
};

const money = (value: unknown) => `$${Number(value || 0).toFixed(3)}`;
const date = (value: string | null) => value ? `${new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" })} UTC` : "Not scheduled";
function countdown(target: string | null, now: number) {
  if (!target) return "Not scheduled";
  const seconds = Math.max(0, Math.floor((new Date(target).getTime() - now) / 1000));
  const days = Math.floor(seconds / 86400), hours = Math.floor((seconds % 86400) / 3600), minutes = Math.floor((seconds % 3600) / 60), secs = seconds % 60;
  return `${days ? `${days}d ` : ""}${hours}h ${minutes}m ${secs}s`;
}

export default function PromoteAdsGalaxyPage() {
  const { setTitle } = useHeader();
  const [data, setData] = React.useState<CampaignData | null>(null);
  const [error, setError] = React.useState("");
  const [copied, setCopied] = React.useState(false);
  const [now, setNow] = React.useState(Date.now());
  const network = "BEP-20";
  const [address, setAddress] = React.useState("");
  const [saving, setSaving] = React.useState(false);
  const [showRewardHelp, setShowRewardHelp] = React.useState(false);
  const load = React.useCallback(() => apiFetch("/api/publisher/promote").then(async r => { const body = await r.json(); if (!r.ok) throw new Error(body.error || "Unable to load campaign"); setData(body); setAddress(body.wallet?.address || ""); }).catch(e => setError(e.message)), []);
  React.useEffect(() => { setTitle("Promote AdsGalaxy"); void load(); }, [setTitle, load]);
  React.useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  async function copyLink() { if (!data?.referral_link) return; await navigator.clipboard.writeText(data.referral_link); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  async function saveWallet() { setSaving(true); setError(""); try { const response = await apiFetch("/api/publisher/promote", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ network, address }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save wallet"); } finally { setSaving(false); } }
  const status = data?.campaign.status || "scheduled";
  if (data?.campaign.payment_completed) return <DashboardLayout type="publisher"><div className="flex min-h-[65vh] items-center justify-center"><section className="relative w-full max-w-3xl overflow-hidden rounded-[2rem] bg-slate-950 p-8 text-center text-white shadow-2xl sm:p-12"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-[#0c9de8]/30 blur-3xl"/><div className="relative"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-500/20 text-emerald-300"><Check size={32}/></div><h1 className="mt-6 text-3xl font-black tracking-tight sm:text-4xl">PROMOTE ADS GALAXY — PAYOUT COMPLETED</h1><p className="mt-6 text-base font-semibold leading-7 text-white/80">Payments have been successfully sent to all eligible participants.</p><p className="mt-2 text-sm leading-6 text-white/65">If you participated in Promote Ads Galaxy, please check your registered wallet for your reward.</p><p className="mt-5 text-sm font-bold text-cyan-200">Thank you for promoting Ads Galaxy and being part of the campaign. 🌌</p></div></section></div></DashboardLayout>;
  const ended = ["closed", "payout_review", "paid", "cancelled"].includes(status);
  const live = status === "active";
  const headlineTimer = live ? `Ends in ${countdown(data?.campaign.ends_at || null, now)}` : ended ? "Campaign ended" : `Starts in ${countdown(data?.campaign.starts_at || null, now)}`;
  const walletWindowOpen = ended && Boolean(data?.campaign.wallet_edit_ends_at) && new Date(data!.campaign.wallet_edit_ends_at!).getTime() > now;
  const cards = [["New referrals", data?.stats.total_referrals || 0, Users], ["Added channels", data?.stats.channel_referrals || 0, Megaphone], ["Pending validation", data?.stats.pending_validation || 0, Clock3], ["Qualified", data?.stats.qualified || 0, ShieldCheck], ["Rejected", data?.stats.rejected || 0, ShieldCheck], ["Campaign earnings", money(data?.stats.campaign_earnings), Check]] as const;
  return <DashboardLayout type="publisher"><div className="space-y-5">
    <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white shadow-2xl"><div className="absolute -right-20 -top-24 h-56 w-56 rounded-full bg-[#0c9de8]/40 blur-3xl"/><div className="relative"><span className="rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-widest text-cyan-100">{ended ? "Ends" : live ? "Live" : "Coming soon"}</span><h1 className="mt-4 text-3xl font-black">Promote AdsGalaxy</h1><p className="mt-2 max-w-2xl text-sm font-medium leading-6 text-white/70">Use this campaign-only link. Eligible referrals still earn the standard $0.005 join and $0.010 verification rewards, but do not count toward Sprints, Teams or referral milestones.</p><p className="mt-4 text-sm font-black text-cyan-200">{headlineTimer}</p></div></section>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
    <section className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Your Promote AdsGalaxy referral link</p><div className="mt-3 flex gap-2 rounded-2xl bg-slate-50 p-2"><span className="min-w-0 flex-1 truncate px-2 py-2 font-mono text-xs text-slate-700">{data?.referral_link || "Loading..."}</span><button onClick={copyLink} disabled={!data?.referral_link} className="flex items-center gap-2 rounded-xl bg-[#0c9de8] px-4 text-xs font-black text-white disabled:opacity-50">{copied ? <Check size={14}/> : <Copy size={14}/>} {copied ? "Copied" : "Copy"}</button></div></section>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{cards.map(([label,value,Icon]) => <div key={label} className="rounded-3xl border border-slate-100 bg-white p-4 shadow-sm"><Icon size={18} className="text-[#0c9de8]"/><p className="mt-3 text-[10px] font-black uppercase tracking-widest text-slate-400">{label}</p><p className="mt-1 text-xl font-black text-slate-950">{value}</p>{label === "Campaign earnings" && ended && <p className="mt-1 text-xs font-bold text-amber-600">Payouts in progress</p>}</div>)}</div>
    <section className="relative overflow-hidden rounded-3xl border border-cyan-100 bg-gradient-to-br from-white via-cyan-50/40 to-blue-50/70 p-5 shadow-sm"><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-cyan-200/30 blur-2xl"/><div className="relative"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-100 text-[#0c9de8]"><Wallet size={18}/></span><h2 className="font-black text-slate-950">Campaign payout wallet</h2></div><p className="mt-3 text-xs leading-5 text-slate-500">Save a USDT BEP-20 wallet after the campaign starts. You can change it until 12 hours after the campaign ends; then it is permanently locked for payout safety.</p>{walletWindowOpen && <p className="mt-2 rounded-xl bg-amber-50 px-3 py-2 text-xs font-black text-amber-700">Wallet locks in {countdown(data?.campaign.wallet_edit_ends_at || null, now)}</p>}{!live && !ended && <p className="mt-3 rounded-xl border border-amber-100 bg-amber-50 px-3 py-2 text-xs font-black text-amber-700">Wallet saving opens when the campaign starts.</p>}{ended && !data?.wallet_editable && <p className="mt-2 text-xs font-black text-red-600">Wallet updates are locked.</p>}<div className="mt-4 grid gap-3 sm:grid-cols-[150px_1fr_auto]"><div className="rounded-xl border border-cyan-100 bg-white/80 px-3 py-3 text-sm font-bold text-slate-700">BEP-20</div><input value={address} onChange={e => setAddress(e.target.value)} disabled={!data?.wallet_editable} placeholder="BEP-20 wallet address (0x...)" className="min-w-0 rounded-xl border border-cyan-100 bg-white px-3 py-3 text-sm outline-none transition focus:border-cyan-400 focus:ring-4 focus:ring-cyan-100"/><button onClick={saveWallet} disabled={saving || !data?.wallet_editable || !address} className="rounded-xl bg-gradient-to-r from-slate-950 to-slate-800 px-5 py-3 text-xs font-black text-white shadow-md disabled:opacity-50">{saving ? "Saving..." : data?.wallet ? "Update wallet" : "Save wallet"}</button></div></div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-blue-100 bg-gradient-to-br from-blue-50/80 to-white p-5 shadow-sm"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-100 text-blue-600"><Clock3 size={18}/></span><h2 className="font-black text-slate-950">Campaign schedule</h2></div><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between gap-4 rounded-xl bg-white/80 px-3 py-3"><dt className="text-slate-500">Starts</dt><dd className="text-right font-bold text-slate-800">{date(data?.campaign.starts_at || null)}</dd></div><div className="flex justify-between gap-4 rounded-xl bg-white/80 px-3 py-3"><dt className="text-slate-500">Ends</dt><dd className="text-right font-bold text-slate-800">{date(data?.campaign.ends_at || null)}</dd></div><div className="flex justify-between gap-4 rounded-xl border border-cyan-100 bg-cyan-50 px-3 py-3"><dt className="font-semibold text-cyan-700">{live ? "Time remaining" : ended ? "Status" : "Countdown"}</dt><dd className="text-right font-black text-cyan-700">{ended ? "Payouts in progress" : headlineTimer}</dd></div></dl></div><div className="rounded-3xl border border-amber-100 bg-gradient-to-br from-amber-50/70 via-white to-cyan-50/50 p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-amber-600">Channel audience rewards</p><h2 className="mt-1 font-black text-slate-950">Fixed rewards</h2></div><button type="button" onClick={() => setShowRewardHelp(true)} aria-label="Explain fixed rewards" className="flex h-10 w-10 items-center justify-center rounded-full border border-amber-200 bg-white text-amber-600 shadow-sm transition active:scale-95"><HelpCircle size={20}/></button></div><p className="mt-2 text-xs leading-5 text-slate-500">Reward depends on the verified audience of the new channel your referral adds.</p><div className="mt-4 space-y-2">{data?.tiers.map((t, index) => <div key={t.minimum} className="flex items-center justify-between rounded-xl border border-white bg-white/90 px-3 py-2.5 text-xs shadow-sm"><span className="flex items-center gap-2 font-semibold text-slate-600"><span className="h-2 w-2 rounded-full bg-gradient-to-r from-amber-400 to-cyan-400"/>{t.minimum.toLocaleString()}-{t.maximum.toLocaleString()} audience</span><strong className="rounded-lg bg-slate-950 px-2.5 py-1.5 text-white">{money(t.amount)}</strong></div>)}</div></div></section>
    <section className="rounded-3xl border border-violet-100 bg-gradient-to-br from-white to-violet-50/60 p-5 text-sm leading-6 text-slate-600 shadow-sm"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-100 text-violet-600"><ShieldCheck size={18}/></span><h2 className="font-black text-slate-950">Rules</h2></div><ul className="mt-4 list-disc space-y-2.5 pl-5 marker:text-violet-400"><li>The referral and their first new channel submission must occur during the active three-day window.</li><li>Only referrals made through your Promote AdsGalaxy campaign link qualify for campaign channel rewards.</li><li>Promote referrals receive only the standard $0.005 join and $0.010 required-channel verification rewards; they do not count toward Sprints, Teams, milestones or first-referral bonuses.</li><li>Old, reactivated, transferred, deleted and re-added channels do not qualify.</li><li>One referred user can generate at most one campaign reward.</li><li>Approval may finish after the campaign ends. Rewards remain pending until audience and fraud validation complete.</li><li>Audience is verified again before payout; the lower valid reward tier is used. Counts above 20,000,000 require manual review.</li><li>Campaign payouts use USDT on BEP-20 only. Wallet saving opens when the campaign starts and locks 12 hours after it ends.</li></ul></section>
    {showRewardHelp && <div className="fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/50 p-4 backdrop-blur-sm sm:items-center" onClick={() => setShowRewardHelp(false)}><div role="dialog" aria-modal="true" aria-labelledby="reward-help-title" onClick={e => e.stopPropagation()} className="w-full max-w-md rounded-[2rem] border border-white/60 bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-widest text-[#0c9de8]">How rewards work</p><h2 id="reward-help-title" className="mt-1 text-xl font-black text-slate-950">Fixed channel rewards</h2></div><button type="button" onClick={() => setShowRewardHelp(false)} aria-label="Close explanation" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-slate-100 text-slate-600"><X size={18}/></button></div><p className="mt-3 text-sm leading-6 text-slate-600">When someone joins through your Promote link and adds a new eligible Telegram channel, the verified audience of that channel determines your campaign reward.</p><div className="mt-4 max-h-64 space-y-2 overflow-y-auto">{data?.tiers.map(t => <div key={t.minimum} className="flex items-center justify-between rounded-xl bg-gradient-to-r from-cyan-50 to-blue-50 px-3 py-3 text-xs"><span className="pr-3 font-semibold leading-5 text-slate-700">{t.minimum.toLocaleString()} to {t.maximum.toLocaleString()} channel audience</span><strong className="shrink-0 text-cyan-700">You earn {money(t.amount)}</strong></div>)}</div><p className="mt-4 rounded-xl bg-amber-50 px-3 py-3 text-xs leading-5 text-amber-800">Example: if your referred user adds an eligible channel with 2,000 to 9,999 verified audience, you earn $0.500.</p><button type="button" onClick={() => setShowRewardHelp(false)} className="mt-4 w-full rounded-xl bg-slate-950 py-3 text-xs font-black uppercase tracking-wide text-white">Got it</button></div></div>}
  </div></DashboardLayout>;
}
