import { NextRequest, NextResponse } from "next/server";
import { timingSafeEqual } from "node:crypto";
import pool from "@/lib/db";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";
import { appendTelegramEntities,contentHash,editTelegramTeaser,stripExactTeaserSuffix,teaserContentFits,type TelegramEntity } from "@/lib/teaser";
import { insertTeaserPlacement } from "@/lib/teaserPlacement";

function authorized(request:NextRequest){const a=Buffer.from(String(process.env.BOT_TOKEN||""));const b=Buffer.from(String(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,""));return a.length>0&&a.length===b.length&&timingSafeEqual(a,b);}
function validEntities(value:unknown):TelegramEntity[]{return Array.isArray(value)?value.filter((v):v is TelegramEntity=>Boolean(v)&&typeof v==="object"&&typeof (v as TelegramEntity).type==="string"&&Number.isInteger((v as TelegramEntity).offset)&&Number.isInteger((v as TelegramEntity).length)):[];}
function parseEntities(value:unknown):TelegramEntity[]{if(Array.isArray(value))return validEntities(value);if(typeof value==="string")try{return validEntities(JSON.parse(value));}catch{return [];}return [];}
async function saveOrganicSnapshot(input:{channelId:number;publisherId:number;updateId:number;chatId:number;messageId:number;messageType:string;text:string;entities:TelegramEntity[];mediaGroupId:string|null;postedAt:number;edited:boolean}){const hash=contentHash(input.text,input.entities);const eligible=["text","photo","video"].includes(input.messageType)&&Boolean(input.text);const [result]=await pool.query<ResultSetHeader>(`INSERT INTO channel_organic_posts(channel_id,publisher_id,telegram_chat_id,telegram_message_id,message_type,organic_text,entities,caption_entities,media_group_id,posted_at,last_organic_edit_at,last_seen_update_id,teaser_eligible,eligibility_reason,content_hash) VALUES(?,?,?,?,?,?,?,?,?,FROM_UNIXTIME(?),${input.edited?"NOW()":"NULL"},?,?,?,?) ON DUPLICATE KEY UPDATE organic_text=VALUES(organic_text),entities=VALUES(entities),caption_entities=VALUES(caption_entities),media_group_id=VALUES(media_group_id),last_organic_edit_at=IF(VALUES(last_seen_update_id)>last_seen_update_id,NOW(),last_organic_edit_at),last_seen_update_id=GREATEST(last_seen_update_id,VALUES(last_seen_update_id)),teaser_eligible=VALUES(teaser_eligible),eligibility_reason=VALUES(eligibility_reason),content_hash=VALUES(content_hash),availability='available',id=LAST_INSERT_ID(id)`,[input.channelId,input.publisherId,input.chatId,input.messageId,input.messageType,input.text,input.messageType==="text"?JSON.stringify(input.entities):null,input.messageType!=="text"?JSON.stringify(input.entities):null,input.mediaGroupId,input.postedAt,input.updateId,eligible?1:0,eligible?null:"POST_UNSUPPORTED",hash]);await pool.query(`DELETE old FROM channel_organic_posts old JOIN (SELECT id FROM channel_organic_posts WHERE channel_id=? ORDER BY telegram_message_id DESC LIMIT 18446744073709551615 OFFSET 5) stale ON stale.id=old.id`,[input.channelId]);return Number(result.insertId);}

type Placement=RowDataPacket&{id:number;channel_id:number;publisher_id:number;telegram_chat_id:number;telegram_message_id:number;message_type:string;organic_text:string;organic_entities:unknown;rendered_suffix:string;rendered_entities:unknown;rendered_content_hash:string;status:string};
async function reconcilePublisherEdit(input:{updateId:number;chatId:number;messageId:number;messageType:string;text:string;entities:TelegramEntity[]}){
  const [rows]=await pool.query<Placement[]>("SELECT * FROM teaser_placements WHERE telegram_chat_id=? AND telegram_message_id=? AND status IN ('active','awaiting_baseline','removal_pending') LIMIT 1",[input.chatId,input.messageId]);const p=rows[0];if(!p)return null;
  if(contentHash(input.text,input.entities)===p.rendered_content_hash)return{ok:true,ignored:"SELF_EDIT"};
  const organic=stripExactTeaserSuffix(input.text,p.rendered_suffix);await saveOrganicSnapshot({channelId:p.channel_id,publisherId:p.publisher_id,updateId:input.updateId,chatId:input.chatId,messageId:input.messageId,messageType:input.messageType,text:organic,entities:input.entities,mediaGroupId:null,postedAt:Math.floor(Date.now()/1000),edited:true});const priorRendered=parseEntities(p.rendered_entities);const teaserEntities=priorRendered.filter(e=>e.offset>=p.organic_text.length).map(e=>({...e,offset:e.offset-p.organic_text.length}));const rendered=appendTelegramEntities(organic,input.entities,{text:p.rendered_suffix,entities:teaserEntities});
  if(!teaserContentFits(input.messageType,rendered.text)){await pool.query("UPDATE teaser_placements SET organic_text=?,organic_entities=?,status='removal_pending',removal_requested_at=NOW(),removal_reason='publisher_edit_capacity' WHERE id=?",[organic,JSON.stringify(input.entities),p.id]);return{ok:true,queued_removal:"CONTENT_CAPACITY"};}
  const edit=await editTelegramTeaser({chatId:input.chatId,messageId:input.messageId,messageType:input.messageType,text:rendered.text,entities:rendered.entities});if(!edit.ok)return{ok:true,retry_required:edit.code};
  await pool.query("UPDATE teaser_placements SET source_update_id=?,message_type=?,organic_text=?,organic_entities=?,rendered_entities=?,rendered_content_hash=?,last_error_code=NULL WHERE id=?",[input.updateId,input.messageType,organic,JSON.stringify(input.entities),JSON.stringify(rendered.entities),contentHash(rendered.text,rendered.entities),p.id]);return{ok:true,reconciled:true};
}

export async function POST(request:NextRequest){
  if(!authorized(request))return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const updateId=Number(body?.update_id),chatId=Number(body?.chat_id),messageId=Number(body?.message_id);
  if(!Number.isSafeInteger(updateId)||!Number.isSafeInteger(chatId))return NextResponse.json({error:"TEASER_EVENT_INVALID"},{status:422});const eventType=body?.event_type==="edited_channel_post"?"edited_channel_post":body?.event_type==="my_chat_member"?"my_chat_member":"channel_post";
  if(eventType==="my_chat_member"){const canEdit=Boolean(body?.can_edit_messages);await pool.query("UPDATE channels SET teaser_status=?,teaser_permission_checked_at=NOW() WHERE chat_id=? AND teaser_enabled=1",[canEdit?"active":"needs_permission",chatId]);if(!canEdit)await pool.query("UPDATE teaser_placements SET status='removal_pending',removal_requested_at=COALESCE(removal_requested_at,NOW()),removal_reason='permission_lost' WHERE telegram_chat_id=? AND status IN ('active','awaiting_baseline')",[chatId]);return NextResponse.json({ok:true});}
  if(!Number.isSafeInteger(messageId)||messageId<=0)return NextResponse.json({error:"TEASER_EVENT_INVALID"},{status:422});const text=String(body?.text||body?.caption||"");const messageType=String(body?.message_type||"text");const incomingEntities=validEntities(body?.entities||body?.caption_entities);if(!text||!["text","photo","video"].includes(messageType))return NextResponse.json({ok:true,skipped:"POST_TYPE_UNSUPPORTED"});
  if(eventType==="edited_channel_post"){const reconciled=await reconcilePublisherEdit({updateId,chatId,messageId,messageType,text,entities:incomingEntities});if(reconciled)return NextResponse.json(reconciled);}
  const conn=await pool.getConnection();try{await conn.beginTransaction();
    const [channels]=await conn.query<Array<RowDataPacket&{id:number;user_id:number;username:string|null;channel_type:string|null;tracking_account:number|null;teaser_daily_limit:number;teaser_last_placement_message_id:number|null}>>(`SELECT ch.id,ch.user_id,ch.username,ch.channel_type,ch.tracking_account,ch.teaser_daily_limit,ch.teaser_last_placement_message_id FROM channels ch JOIN settings s ON s.key='teaser_enabled' AND s.value='1' WHERE ch.chat_id=? AND ch.is_deleted=FALSE AND ch.status IN ('active','approved') AND ch.teaser_enabled=1 AND ch.teaser_status='active' LIMIT 1 FOR UPDATE`,[chatId]);const channel=channels[0];if(!channel){await conn.rollback();return NextResponse.json({ok:true,skipped:"CHANNEL_NOT_ELIGIBLE"});}
    const organicPostId=await saveOrganicSnapshot({channelId:channel.id,publisherId:channel.user_id,updateId,chatId,messageId,messageType,text,entities:incomingEntities,mediaGroupId:body?.media_group_id?String(body.media_group_id):null,postedAt:Number(body?.posted_at)||Math.floor(Date.now()/1000),edited:false});
    await conn.query("UPDATE channels SET teaser_last_organic_message_id=? WHERE id=?",[messageId,channel.id]);
    await conn.commit();
    return NextResponse.json(await insertTeaserPlacement({sourceUpdateId:updateId,channelId:channel.id,snapshot:{id:organicPostId,channel_id:channel.id,publisher_id:channel.user_id,telegram_chat_id:chatId,telegram_message_id:messageId,message_type:messageType,organic_text:text,entities:messageType==="text"?incomingEntities:null,caption_entities:messageType!=="text"?incomingEntities:null,content_hash:contentHash(text,incomingEntities)}}));
  }catch(error){await conn.rollback().catch(()=>undefined);console.error("Teaser ingestion failed",{code:error instanceof Error?error.name:"UNKNOWN"});return NextResponse.json({error:"TEASER_INGESTION_FAILED"},{status:500});}finally{conn.release();}
}
