import DocsArticle, { type DocsSection } from "@/components/docs/DocsArticle";

const appOrigin = (
  process.env.NEXT_PUBLIC_APP_URL
  || process.env.NEXT_PUBLIC_ADSGALAXY_APP_URL
  || "https://app.adsgalaxy.online"
).replace(/\/$/, "");

const webhookUrlExample = `${appOrigin}/api/bot/webhook/YOUR_BOT_ID/YOUR_SIGNED_SECRET`;

const webhookSetupExample = `curl -X POST "https://api.telegram.org/botYOUR_BOT_TOKEN/setWebhook" \\
     -H "Content-Type: application/json" \\
     -d '{"url": "${webhookUrlExample}"}'`;

const sections: DocsSection[] = [
  {
    id: "overview",
    title: "How bot monetization works",
    body: [
      "Bot monetization lets approved Telegram bot owners earn from eligible advertiser broadcast delivery.",
      "AdsGalaxy uses approved bot details and reachable bot users to determine campaign delivery opportunities.",
    ],
  },
  {
    id: "requirements",
    title: "Requirements",
    body: ["Submit real bots with authentic users and compliant content. Bots with artificial activity or misleading identities can be rejected."],
    bullets: [
      "Bot name: the readable bot name shown in your dashboard.",
      "Bot username: the Telegram bot username.",
      "Bot token or required connection details: used by the platform to verify and manage the bot integration where required by the form.",
      "Users: imported or collected users must represent real reachable Telegram users.",
    ],
  },
  {
    id: "add-bot",
    title: "Add bot flow",
    body: [
      "Open Publisher > Monetize > Bot, add the bot details, and submit the bot for review.",
      "After approval, keep the bot active and maintain healthy user collection so eligible broadcasts can be delivered.",
    ],
  },
  {
    id: "webhook-setup",
    title: "Bot webhook setup",
    body: [
      "Open Publisher > Monetize > Bot > View Details and copy the Bot Webhook URL from Webhook Setup.",
      `The miniapp provides a URL in this exact format: ${webhookUrlExample}. YOUR_BOT_ID and YOUR_SIGNED_SECRET are generated by AdsGalaxy in the copied URL, so do not replace them manually.`,
      "Set that copied URL through Telegram's setWebhook method. Replace only YOUR_BOT_TOKEN in the command below, and keep that token private.",
    ],
    bullets: [
      "Configured means Telegram is using the current AdsGalaxy URL.",
      "Receiving users means AdsGalaxy has accepted at least one update through that webhook.",
    ],
    code: { language: "bash", value: webhookSetupExample },
  },
  {
    id: "users",
    title: "Importing users",
    body: [
      "The bot area includes user management tools. Import only legitimate users who interacted with your bot or are otherwise valid for Telegram delivery.",
      "Healthy user lists improve delivery reliability and reduce review issues.",
    ],
  },
  {
    id: "reporting",
    title: "Reporting, earnings, and withdrawals",
    body: [
      "Bot reporting focuses on delivery activity and bot status. Earnings appear after eligible broadcast delivery and platform processing.",
      "Withdrawals use the normal publisher withdrawal flow and available balance rules.",
    ],
  },
];

export default function PublisherBotsDocsPage() {
  return (
    <DocsArticle
      eyebrow="Publisher Documentation"
      title="Bot Monetization"
      intro="Connect Telegram bots, manage reachable users, and monetize approved broadcast delivery."
      sections={sections}
    />
  );
}
